### ISSUE TITLE
flutter_icmp_ping not work Android

### ISSUE THREAD

**Issue by tungvt80** [zuvola/flutter_icmp_ping#8]
flutter_icmp_ping notwork Android. May be Fix

**Comment by zuvola** [comment]
Sorry for the late reply.
I have corrected it, so please check it.

**Comment by InTheClodus** [comment]
> Sorry for the late reply. I have corrected it, so please check it.

The problem has not been fixed, I checked the FlutterIcmpPingPlugin.kt file, did not see any code related to ping

**Comment by zuvola** [comment]
Android does not use the plugin.
FlutterIcmpPingPlugin.kt is a dummy file to be published to Pub.dev.
Please refer to dart files for how it works on Android.
